### ISSUE TITLE
Can't find the extension in the marketplace

### ISSUE THREAD

**Issue by joelostblom** [ExecutableBookProject/myst-highlight-grammar#21]
**Describe the bug**
When I try `ext install ExecutableBookProject.myst-highlight` in the quick open box, it searches for this name in the marketplace but nothing relevant is found. I tried searching for different parts of the name, but can't find anything that looks like the correct extension. I'm on Linux so possible related to https://github.com/executablebooks/myst-language-support/issues/20? I'm relatively new to VS Code, so it is possible I'm missing something obvious here.

![image](https://user-images.githubusercontent.com/4560057/109407130-3e460000-7933-11eb-8fef-145890c44bb6.png)

**Desktop (please complete the following information):**

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T21:13:58.622Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.1-arch1-1
```

**Comment by joelostblom** [comment]
Figured it out, turns out the default Arch install of vscode points to [an open marketplace](https://open-vsx.org/) rather thean the MS marketplace. [Changing this fixed it.](https://stackoverflow.com/a/37238623/2166823)

**Comment by chrisjsewell** [comment]
Ah good
