### ISSUE TITLE
{eval}  gives unexecuted inline expression error only if edited in vscode

### ISSUE THREAD

**Issue by jhconning** [ExecutableBookProject/myst-highlight-grammar#61]
**Describe the bug**
`{eval}` role expressions lead to an _Unexecuted inline expression_ error when the notebook cell is evaluated in vs-code but works as expected when the same notebook and cell is evaluated in jupyter lab.

**To Reproduce**
1. Open a notebook in vscode with myst markdown extension.
2. Create python and markdown cells. The example in the screenshots below uses:
```
The sum of the first TEN numbers is {eval}`array.sum()`
```
3. run `myst start` from the CLI to see rendered output.
4. See error in rendered output in screenshots below.

**Expected behavior**
When I edit the same notebook and cells using jupyterlab, things are rendered correctly.  See the second screenshot below.

**Screenshots**
When edited in vscode:
![image](https://github.com/user-attachments/assets/89f42be2-4d00-4179-966d-2cac334de9ca)

When edited in juptyerlab:
![image](https://github.com/user-attachments/assets/e121b64f-563d-4d4f-8682-a9b03df7e222)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
I'm puzzled and apologize if I may be posting this to the wrong repo.  I would have thought the myst extension mainly affects syntax highlighting and preview within vscode and would not affect how ipynb or md files are processed and rendered by the myst server.  However, the only observable difference is whether I edit in vscode or in jupyter lab.

**Comment by rowanc1** [comment]
To execute these through the command line in mystmd you can use `myst start --execute`, which does respect inline expressions. You are right that the vscode plugin does not yet render inline expressions, and that functionality is only possible through `jupyterlab-myst` (in JupyterLab) and `mystmd` (on the command line).

**Comment by jhconning** [comment]
Thanks for the clarification, I'll do that!
