### ISSUE TITLE
insider vscode?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/myst-highlight-grammar#7]
I am super excited to give this a try :-)

however, vscode tells me I can't install it because I'm running the insider version of it. Is it trivial to support insider versions? (I'm in 1.38-insider), or do you recommend I move to the stable branch?

(I think it's fine for me to move to stable if that's the best option, I had switched to insider a few months back because of some improvements in their remote server plugin, but I think those are in stable now)

**Comment by chrisjsewell** [comment]
I'd be happy to if I knew how??
From a quick google, and when I've looked at other extensions, I don't see any specific option to add to the package, to say that insiders is supported.
You'd have to look into this

**Comment by choldgraf** [comment]
ok cool, I'll just try moving to stable then 👍

**Comment by chrisjsewell** [comment]
yeh definitely go for it. I ironed out a few kinks and now it’s working really well for me

**Comment by choldgraf** [comment]
awesome! vs code stable has it working!

is there something else we should install to get syntax completion (either in code blocks, or for things like sphinx) working? I see markdown highlighting is working great, but don't seem to be getting autocompletion

(note, intellisense does seem to work for python files)

**Comment by chrisjsewell** [comment]
This is only a static syntax highlighter at present, i.e. in doesn't do any active analysis on the file in the way an LSP does (above what VS Code or any extensions you have installed are already doing for markdown files). So when e.g. it reaches a python code cell, it will set the 'scope' to be python; which hooks in some limited features, e.g. syntax highlghting, correct commenting format (when you press CMD+/) and snippet completion (try pressing CTRL+Space):

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2997570/77113222-52df0000-6a22-11ea-9ed9-a1a0259b2c04.png">

and as it says now in the README, I have also added a few directive snippets:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2997570/77113455-c54fe000-6a22-11ea-8992-4c176ff0842d.png">

Note, you can see the language scope you are in using the `Developer: Inspect TM Scopes` command, which is super helpful for developing/checking the highlight grammar:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2997570/77114025-c2092400-6a23-11ea-8e65-64f441fbe71f.png">

For proper syntax completion etc, this is where an LSP comes in; to be actively compiling a database of syntax elements, by source text ranges, mapping that to the current cursor position (supplied by the client), and reporting back to the client with data such as autocompletion lists.

**Comment by choldgraf** [comment]
ah ok, I figured it out - I was overriding the keyboard shortcut to bring up intellisense, and now I have discovered a whole new feature of vscode lol.

Being able to quickly get a list of directives to insert is *awesome*

**Comment by chrisjsewell** [comment]
> Being able to quickly get a list of directives to insert is awesome

Absolutely, it's a nice quick win, as opposed to potentially/hopefully writing a more feature rich LSP somewhere down the line.

As a user you can add your own custom snippets (see the VS Code docs), or the ones packaged with the extension are implemented with this template/build file: https://github.com/ExecutableBookProject/myst-highlight-grammar/tree/master/snippets

So if you wanted to add additional ones here, feel free to make a PR 😄

**Comment by choldgraf** [comment]
To check that I am correct, if I wanted to add, say, a glue directive, it would look like this:

```
  "directive-glue": {
    "description": "a glue directive",
    "prefix": [
      "directive-glue"
    ],
    "body": [
      "```{glue:${1:directive}} ${0:key}",
      "```",
      ""
    ]
  }
```

and if I wanted to add a role, it would look something like this?

```
  "role-glue": {
    "description": "a glue role",
    "prefix": [
      "role-glue"
    ],
    "body": [
      "{glue}`${0:key}`",
    ]
  }
```

Also - looking at the docs, why do we have the first `$1` at the end of the triple backticks?

**Comment by chrisjsewell** [comment]
👍 

> Also - looking at the docs, why do we have the first $1 at the end of the triple backticks?

The idea was that you can quickly modify the 'nesting depth' of your directives: press enter on the snippet, press `` ` ``, then press tab, and you now have a directive enclosed by 4 backticks instead of 3.
Its an open question if this is a help or a hindrance

**Comment by choldgraf** [comment]
ah ha - I hadn't thought about that use-case...but it makes sense to me! I'm sure I would have run across this when I was doing more docs work with this plugin

**Comment by chrisjsewell** [comment]
Yeh just keep using it and report back any bugs! 

This was a particular gotcha with this new injection approach ccff42658c2433ad0d383178ad790b0dc0ea9a42, whereby it was incorrectly injecting into things like math and code blocks,  but hopefully this is fixed.

**Comment by chrisjsewell** [comment]
and there might be fine-tuning to the name scope for each element is assigned (which affects e.g.what color it is assigned)

**Comment by choldgraf** [comment]
makes sense 👍 

are there ways to define "sub-commands" in the schema? e.g. if we wanted to say "if someone chooses the glue directive, then give them the option of `:figure`, `:text`, etc? or would each of those need to be separate entries in the schema?

**Comment by chrisjsewell** [comment]
No, again this is where an LSP/active extension comes in.
